name: AXIS-Adder Pre-Commit Workflow
on: 
  workflow_dispatch:
  push:
    branches:    
      - main
jobs:
  AXIS-Adder-Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Icarus Verilog
        run: sudo apt install iverilog
      - name: Build
        run: make build
      - name: Simulation
        run: make sim | tee log.txt
      - name: Check Results
        run: |
          if grep -q PASS log.txt; then
            exit 0
          else
            exit 1
          fi
